from __future__ import annotations

from app.rbac.rbac_seed import (
    BILLING_ACCESS,
    CRM_DELETE,
    CRM_READ,
    CRM_WRITE,
    REPORTING_READ,
    SALES_DELETE,
    SALES_READ,
    SALES_WRITE,
    SUPPORT_READ,
    SUPPORT_WRITE,
    TENANT_ADMIN,
)

# Canonical exported permission constants for route/service enforcement.

PERMISSION_CRM_READ = CRM_READ
PERMISSION_CRM_WRITE = CRM_WRITE
PERMISSION_CRM_DELETE = CRM_DELETE

PERMISSION_SALES_READ = SALES_READ
PERMISSION_SALES_WRITE = SALES_WRITE
PERMISSION_SALES_DELETE = SALES_DELETE

PERMISSION_REPORTING_READ = REPORTING_READ

PERMISSION_SUPPORT_READ = SUPPORT_READ
PERMISSION_SUPPORT_WRITE = SUPPORT_WRITE

PERMISSION_BILLING_ACCESS = BILLING_ACCESS
PERMISSION_TENANT_ADMIN = TENANT_ADMIN


ALL_PERMISSIONS: tuple[str, ...] = (
    PERMISSION_CRM_READ,
    PERMISSION_CRM_WRITE,
    PERMISSION_CRM_DELETE,
    PERMISSION_SALES_READ,
    PERMISSION_SALES_WRITE,
    PERMISSION_SALES_DELETE,
    PERMISSION_REPORTING_READ,
    PERMISSION_SUPPORT_READ,
    PERMISSION_SUPPORT_WRITE,
    PERMISSION_BILLING_ACCESS,
    PERMISSION_TENANT_ADMIN,
)